version: '3.8'
services:
  web:
    image: 'suhlig/journal' # for dev, use "build ." instead
    ports:
     - "4567:4567"
    environment:
      RACK_ENV: production
      PORT: 4567
      DB: "postgres://vagrant:vagrant@db/journal"
    depends_on:
      - db

  db:
    image: 'postgres:alpine'
    environment:
      POSTGRES_USER: vagrant
      POSTGRES_PASSWORD: vagrant
      POSTGRES_DB: journal
